### ISSUE TITLE
Kueue Env Configuration for Skaha

### ISSUE THREAD

**Issue by shinybrar** [opencadc/deployments#27]
- Local Queue Configuration
```yaml
metadata:
  namespace: skaha-workload
  name: skaha-local-queue
```
```yaml
metadata:
  namespace: canfar-b-workload
  name: canfar-b-local-queue

```
- Priority Classes
```yaml
---
# WorkloadPriorityClass
apiVersion: kueue.x-k8s.io/v1beta1
kind: WorkloadPriorityClass
metadata:
  name: low
value: 10000
description: "Low Priority"
---
# WorkloadPriorityClass
apiVersion: kueue.x-k8s.io/v1beta1
kind: WorkloadPriorityClass
metadata:
  name: medium
value: 100000
description: "Medium Priority"
---
# WorkloadPriorityClass
apiVersion: kueue.x-k8s.io/v1beta1
kind: WorkloadPriorityClass
metadata:
  name: high
value: 1000000
description: "High Priority"
```

The Skaha Metadata for a job should look something like this,
```yaml
apiVersion: batch/v1
kind: Job
metadata:
  name: sample-job
  labels:
    kueue.x-k8s.io/queue-name: canfar-b-workload
    kueue.x-k8s.io/priority-class: high
```
